[package]
name = "defamed_test"
version = "0.1.0"
edition = "2021"

[lib]
name = "defamed_test"
path = "src/lib.rs"

[[bin]]
name = "test_bin"
path = "src/main.rs"

[dependencies]
defamed = { path = "../defamed" }
