[package]
name = "defamed-test"
version = "0.1.0"
edition = "2021"

[dependencies]
defamed = { path = "../defamed" }
defamed-test-lib = { path = "../defamed-test-lib" }

syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
